# Site settings
title: The World is on Sale
description: >
  British Airways are holding a sale that will see you jet-setting around the world in no time. Take advantage of these incredible discounted flights to some of the world’s most exclusive travel destinations.
baseurl: "/britishairwaysworldsale" # the subpath of your site, e.g. /blog/
url: "http://mp.secretescapes.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, bower_components, bower.json, README.md, npm-debug.log]

campaign-link: https://ad.doubleclick.net/ddm/clk/281431668;200931936;h?http://www.britishairways.com/en-gb/offers/sale?DM1_Channel=TS&DM1_Campaign=UKI_GB_EN_Secretescapes_JulySale17landingpage&DM1_Site=Secretescapes&utm_source=Secretescapes&utm_medium=Partners&utm_campaign=UKI_GB_EN_Secretescapes_JulySale17landingpage&utm_term=SR